from datetime import datetime
from fpdf import FPDF
import streamlit as st
import joblib

import numpy as np

st.set_page_config(
    page_title="HeartCare AI",
    page_icon="❤️",
    layout="wide",
    initial_sidebar_state="expanded"
)
with st.sidebar:
    st.image("https://img.icons8.com/color/96/heart-with-pulse.png", width=80)
    st.title("HeartCare AI")

    st.markdown("---")

    st.success("✅ Logistic Regression Model")

    st.markdown("""
### Navigation

🏠 Home

❤️ Prediction

📊 Dashboard *(Coming Soon)*

🤖 AI Assistant *(Coming Soon)*

📄 Report *(Coming Soon)*

ℹ About
""")

    st.markdown("---")
    st.info("Developed by\n\nPujitha Chowdary")
# Load the trained model
model = joblib.load('heart_attack_model.pkl')


def create_pdf(age, gender, prediction_text, confidence,
               health_score, bmi, water_intake):

    pdf = FPDF()
    pdf.add_page()

    # Title
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 8, f"Generated on: {datetime.now().strftime('%d-%m-%Y %I:%M %p')}", ln=True)
    pdf.ln(5)
    pdf.set_font("Arial", "B", 20)
    pdf.cell(0, 12, "HeartCare AI Report", ln=True, align="C")

    pdf.ln(8)

    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Patient Details", ln=True)

    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 8, f"Age: {age}", ln=True)
    pdf.cell(0, 8, f"Gender: {gender}", ln=True)
    pdf.cell(0, 8, f"Prediction: {prediction_text}", ln=True)
    pdf.cell(0, 8, f"Confidence: {confidence:.2f}%", ln=True)
    pdf.cell(0, 8, f"Heart Health Score: {health_score}/100", ln=True)
    pdf.cell(0, 8, f"BMI: {bmi:.1f}", ln=True)
    pdf.cell(0, 8, f"Recommended Water Intake: {water_intake:.1f} L/day", ln=True)

    pdf.ln(8)

    # Diet Recommendation
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Diet Recommendation", ln=True)

    pdf.set_font("Arial", "", 12)

    diet = [
        "- Eat more fruits and vegetables",
        "- Choose whole grains",
        "- Eat lean proteins like fish and chicken",
        "- Drink plenty of water",
        "- Avoid oily foods",
        "- Reduce salt intake",
        "- Avoid sugary drinks",
        "- Limit processed foods"
    ]

    for item in diet:
        pdf.cell(0, 8, item, ln=True)

    pdf.ln(5)

    # Exercise Recommendation
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Exercise Recommendation", ln=True)

    pdf.set_font("Arial", "", 12)

    exercise = [
        "- Walk 30 minutes daily",
        "- Perform light stretching",
        "- Do yoga or meditation",
        "- Avoid prolonged sitting",
        "- Sleep 7-8 hours daily"
    ]

    for item in exercise:
        pdf.cell(0, 8, item, ln=True)

    pdf.ln(5)

    # Heart Health Tips
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Heart Health Tips", ln=True)

    pdf.set_font("Arial", "", 12)

    tips = [
        "- Monitor blood pressure regularly",
        "- Maintain healthy body weight",
        "- Avoid smoking",
        "- Limit alcohol consumption",
        "- Take medicines as prescribed",
        "- Visit your doctor regularly"
    ]

    for item in tips:
        pdf.cell(0, 8, item, ln=True)

    pdf.ln(10)

    pdf.set_font("Arial", "I", 11)
    pdf.multi_cell(
        0,
        7,
        "This report is generated by HeartCare AI for educational purposes only and should not replace professional medical advice."
    )

    pdf.output("HeartCare_Report.pdf")


# App Title
st.title("❤️ HeartCare AI")

st.subheader("Intelligent Heart Attack Risk Prediction System")

st.markdown("""
Predict heart attack risk using a Machine Learning model.

⚠️ **Note:** This application is for educational purposes only and should not replace professional medical advice.
""")
col1, col2, col3, col4 = st.columns(4)

with col1:
    st.success("🤖 AI Powered")

with col2:
    st.info("⚡ Instant Prediction")

with col3:
    st.warning("❤️ Heart Analysis")

with col4:
    st.error("📈 Logistic Regression")

st.divider()

st.subheader("📝 Patient Health Details")

st.write("Enter the patient details below to predict heart attack risk.")

# User Inputs
age = st.number_input("Age", min_value=1, max_value=120)

sex = st.selectbox(
    "Sex",
    options=[0, 1],
    format_func=lambda x: "Female" if x == 0 else "Male"
)

cp = st.number_input("Chest Pain Type (0-3)", min_value=0, max_value=3)

trestbps = st.number_input("Resting Blood Pressure")

chol = st.number_input("Cholesterol")

fbs = st.selectbox(
    "Fasting Blood Sugar > 120 mg/dl",
    options=[0, 1],
    format_func=lambda x: "No" if x == 0 else "Yes"
)

restecg = st.number_input("Rest ECG (0-2)", min_value=0, max_value=2)

thalach = st.number_input("Maximum Heart Rate")

exang = st.selectbox(
    "Exercise Induced Angina",
    options=[0, 1],
    format_func=lambda x: "No" if x == 0 else "Yes"
)

oldpeak = st.number_input("Oldpeak", format="%.1f")

slope = st.number_input("Slope (0-2)", min_value=0, max_value=2)

ca = st.number_input("Number of Major Vessels (0-4)", min_value=0, max_value=4)

thal = st.number_input("Thal (0-3)", min_value=0, max_value=3)
st.divider()
st.subheader("⚖️ BMI Calculator")

col1, col2 = st.columns(2)

with col1:
    height = st.number_input(
        "Height (cm)",
        min_value=50.0,
        max_value=250.0,
        value=170.0
    )

with col2:
    weight = st.number_input(
        "Weight (kg)",
        min_value=10.0,
        max_value=300.0,
        value=70.0
    )

bmi = weight / ((height / 100) ** 2)

st.metric("BMI", f"{bmi:.1f}")

if bmi < 18.5:
    st.info("⚠️ Underweight")
elif bmi < 25:
    st.success("✅ Normal Weight")
elif bmi < 30:
    st.warning("⚠️ Overweight")
else:
    st.error("🚨 Obese")
st.divider()

st.subheader("💧 Daily Water Intake")

water_intake = weight * 0.033

st.metric("Recommended Water Intake", f"{water_intake:.1f} Litres/day")

if water_intake < 2:
    st.info("💧 Drink at least 2 litres of water every day.")
else:
    st.success(f"💧 Recommended daily water intake: {water_intake:.1f} Litres")


# Prediction Button
if st.button("Predict"):

    input_data = np.array([[age, sex, cp, trestbps,
                            chol, fbs, restecg,
                            thalach, exang,
                            oldpeak, slope,
                            ca, thal]])

    prediction = model.predict(input_data)

    probability = model.predict_proba(input_data)[0]

    if prediction[0] == 1:
        confidence = probability[1] * 100
    else:
        confidence = probability[0] * 100

    st.divider()

    st.subheader("❤️ Prediction Result")
    st.subheader("📈 Risk Meter")

    risk_percentage = confidence if prediction[0] == 1 else (100 - confidence)

    st.progress(int(risk_percentage))

    st.write(f"**Risk Level:** {risk_percentage:.1f}%")

    if risk_percentage < 30:
        st.success("🟢 Low Risk")
    elif risk_percentage < 70:
        st.warning("🟡 Moderate Risk")
    else:
        st.error("🔴 High Risk")
    st.write("")    
    st.divider()

    st.subheader("📋 Patient Summary")

    gender = "Male" if sex == 1 else "Female"
    fbs_status = "Yes" if fbs == 1 else "No"
    angina = "Yes" if exang == 1 else "No"

    col1, col2 = st.columns(2)

    with col1:
        st.info(f"""
    👤 **Age:** {age}

    🚻 **Gender:** {gender}

    ❤️ **Chest Pain Type:** {cp}

    🩸 **Blood Pressure:** {trestbps} mmHg

    🧪 **Cholesterol:** {chol} mg/dL

    🍬 **Fasting Blood Sugar:** {fbs_status}
    """)

    with col2:
        st.info(f"""
    📈 **Rest ECG:** {restecg}

    ❤️ **Maximum Heart Rate:** {thalach} bpm

    🏃 **Exercise Angina:** {angina}

    📉 **Oldpeak:** {oldpeak}

    ⚖️ **BMI:** {bmi:.1f}

    💧 **Water Intake:** {water_intake:.1f} L/day
    """)

    if prediction[0] == 1:
        st.error("🔴 High Risk of Heart Attack")

        col1, col2 = st.columns(2)

        with col1:
            st.metric("Confidence Score", f"{confidence:.2f}%")

        with col2:
            health_score = round(100 - confidence)
            st.metric("❤️ Heart Health Score", f"{health_score}/100")

        st.warning("Please consult a doctor immediately.")
        st.subheader("🥗 Diet Recommendation")

        st.markdown("""
        ✅ Eat more fruits and vegetables

        ✅ Choose whole grains

        ✅ Eat lean proteins like fish and chicken

        ✅ Drink plenty of water

        ❌ Avoid oily foods

        ❌ Reduce salt intake

        ❌ Avoid sugary drinks

        ❌ Limit processed foods
        """)
        st.subheader("🏃 Exercise Recommendation")

        st.markdown("""
        🚶 Walking – 20 to 30 minutes daily

        🧘 Light Yoga

        💨 Breathing Exercises

        🚴 Light Cycling

        😴 Get 7–8 hours of sleep

        ❌ Avoid heavy workouts without consulting a doctor.
        """)
        st.divider()

        st.subheader("❤️ Heart Health Tips")

        st.info("""
        🩺 Schedule regular heart checkups.

        🚭 Quit smoking and avoid alcohol.

        🥗 Eat a heart-healthy diet rich in fruits and vegetables.

        🧂 Reduce salt and sugar intake.

        💧 Drink enough water every day.

        😴 Sleep at least 7–8 hours daily.

        🧘 Practice yoga and meditation to reduce stress.

        💊 Take medicines only as prescribed by your doctor.
        """)
        

    else:
        st.success("🟢 Low Risk of Heart Attack")

        col1, col2 = st.columns(2)

        with col1:
            st.metric("Confidence Score", f"{confidence:.2f}%")

        with col2:
            health_score = round(confidence)
            st.metric("❤️ Heart Health Score", f"{health_score}/100")

        st.info("Maintain a healthy lifestyle.")
        st.subheader("🥗 Diet Recommendation")

        st.markdown("""
        ✅ Continue eating a balanced diet

        ✅ Include fruits and vegetables daily

        ✅ Eat nuts and seeds

        ✅ Drink 2–3 litres of water

        ✅ Eat low-fat dairy products

        ✅ Maintain a healthy weight
        """)
        st.subheader("🏃 Exercise Recommendation")

        st.markdown("""
        🏃 Jogging – 30 minutes daily

        🚴 Cycling

        🏊 Swimming

        🏋️ Strength Training (3–4 days/week)

        🧘 Yoga & Meditation

        💧 Stay hydrated during workouts.
        """)
        st.divider()

        st.subheader("❤️ Heart Health Tips")

        st.success("""
        ❤️ Continue your healthy lifestyle.

        🏃 Exercise for at least 30 minutes daily.

        🥗 Eat a balanced diet.

        💧 Stay hydrated.

        😴 Maintain good sleep habits.

        🧘 Manage stress through meditation or yoga.

        🩺 Go for regular health checkups.

        🚭 Avoid smoking and limit alcohol consumption.
        """)
    prediction_text = "High Risk" if prediction[0] == 1 else "Low Risk"
    gender = "Male" if sex == 1 else "Female"

    

    create_pdf(
        age,
        gender,
        prediction_text,
        confidence,
        health_score,
        bmi,
        water_intake
    )
               

    with open("HeartCare_Report.pdf", "rb") as pdf_file:
        st.download_button(
            label="⬇ Download PDF",
            data=pdf_file,
            file_name="HeartCare_Report.pdf",
            mime="application/pdf"
        )
            


st.markdown("""
<div style="text-align:center; padding:20px; color:gray;">
    <h4>❤️ HeartCare AI</h4>
    <p><b>Developed by Pujitha Chowdary</b></p>
    <p>B.Tech – Data Science</p>
    <p>NRI Institute of Technology</p>
    <p><i>Machine Learning Based Heart Attack Risk Prediction System</i></p>
</div>
""", unsafe_allow_html=True)
